language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
install:
  - pip install -r requirements.txt
  - pip freeze
script:
  - pytest
branches:
  only:
    # This prevents double building for a PR
    - master
    # Aso build on version tags matching this super basic version regex.
    - /^v\d+.*$/
jobs:
  include:
    - stage: release
      python: '3.6'
      env: skip
      script: skip
      install: skip

      deploy:
        provider: pypi
        user: plangrid
        password:
          secure: njTgeelIENdMmwJLd3R6A5Wb1MmMt1fJIItjVOUnmJzs/ezqGNo5XlNOU13PUclTdk9mumfD/8QTkJ5MB7VAPLHr36XMzKiFlxgHp70qQtr9/E8oX2++2D4spmQ+35tXbl/zPiNQOWXZBpfi84nSMSCZ+3beaYxyW1l39TGaS/dhokwQiSYGcGsaz4a5FnHaa2K9XxVV1SSgHKDzMOTZz2wUWn+wxlBsQqPx399RIzGiAeDKgYcJqBIgo7Bn98i+u96MSXEOFH3iDdwdjljCeNmP2o1x96nNBxQhS2mOCR4nkqbXo1o4ZxDAJ1RNwqDXZveEIFgFmLuAPiWI8ZosSXs4Q3oL10KOPg83jTdli68p+W6vwtd7WSMkuUoM/yPSWnLISGXnz5kuhVPr69rsbZ7xmkUzxmSvmz4JkMRTmnZvOG794t2mlsTXdP9XCzBrHntZkmhSTL/SzFhWnJhrkAyhlOEBptzles2OExsFR3eRmaspu1mpl8O2MqrugzvlqUq/sKxOGB7VQ5pUFB1g9ZUxVqXZg1yTAR17pkEcD8NZP+RzsDf5We6V0gQ0O2WB8x5iFzdCVfVG6W1Tc9RlkMkbtUyC2c7D6+C58C4Mjm6BJ+NE6rjoNXDUqa2v9qmmVD6x8lCMyiV5pQjuTUJgedQP80qFuQ8V4hI68CcBNWs=
        on:
          tags: true
